import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { faSquareCheck } from '@fortawesome/free-solid-svg-icons/faSquareCheck'
import { faHouse } from '@fortawesome/free-solid-svg-icons/faHouse'
import { faComment } from '@fortawesome/free-solid-svg-icons/faComment'
import { faBookOpen } from '@fortawesome/free-solid-svg-icons/faBookOpen'
import { faChartSimple } from '@fortawesome/free-solid-svg-icons/faChartSimple'
import { faPaperclip } from '@fortawesome/free-solid-svg-icons/faPaperclip'
import { faEllipsisVertical } from '@fortawesome/free-solid-svg-icons/faEllipsisVertical'
import { faPlaneDeparture } from '@fortawesome/free-solid-svg-icons/faPlaneDeparture'
import { faCalendarCheck } from '@fortawesome/free-solid-svg-icons/faCalendarCheck'
import { faAddressCard } from '@fortawesome/free-solid-svg-icons/faAddressCard'
import { faCheck } from '@fortawesome/free-solid-svg-icons/faCheck'
import { faCircleCheck } from '@fortawesome/free-solid-svg-icons/faCircleCheck'
import { faXmark } from '@fortawesome/free-solid-svg-icons/faXmark'
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons/faArrowLeft'
import { faArrowRight } from '@fortawesome/free-solid-svg-icons/faArrowRight'
import { faHouseUser } from '@fortawesome/free-solid-svg-icons/faHouseUser'
import { faShare } from '@fortawesome/free-solid-svg-icons/faShare'
import { faFileExport } from '@fortawesome/free-solid-svg-icons/faFileExport'
import { faPenToSquare } from '@fortawesome/free-solid-svg-icons/faPenToSquare'
import { faCalendar } from '@fortawesome/free-solid-svg-icons/faCalendar'
import { faFilter } from '@fortawesome/free-solid-svg-icons/faFilter'
import { faArrowUpZA } from '@fortawesome/free-solid-svg-icons/faArrowUpZA'
import { faArrowUpAZ } from '@fortawesome/free-solid-svg-icons/faArrowUpAZ'
import { faArrowUp91 } from '@fortawesome/free-solid-svg-icons/faArrowUp91'
import { faArrowUp19 } from '@fortawesome/free-solid-svg-icons/faArrowUp19'
import { faPersonArrowUpFromLine } from '@fortawesome/free-solid-svg-icons/faPersonArrowUpFromLine'
import { faPersonArrowDownToLine } from '@fortawesome/free-solid-svg-icons/faPersonArrowDownToLine'
import { faToggleOn } from '@fortawesome/free-solid-svg-icons/faToggleOn'
import { faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons/faMagnifyingGlass'
import { faGear } from '@fortawesome/free-solid-svg-icons/faGear'
import { faUserCheck } from '@fortawesome/free-solid-svg-icons/faUserCheck'
import { faBullhorn } from '@fortawesome/free-solid-svg-icons/faBullhorn'
import { faPersonChalkboard } from '@fortawesome/free-solid-svg-icons/faPersonChalkboard'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons/faArrowDown'
import { faClock } from '@fortawesome/free-solid-svg-icons/faClock'



export function initializeIconLibrary() {
  library.add(fab, faGear, faClock, faArrowDown, faPersonChalkboard, faBullhorn, faUserCheck, faMagnifyingGlass, faArrowUpZA, faToggleOn, faArrowUpAZ, faArrowUp91, faArrowUp19, faPersonArrowUpFromLine, faPersonArrowDownToLine, faFilter, faArrowRight, faFilter, faCircleCheck, faCalendar, faPenToSquare, faShare, faHouseUser, faFileExport, faArrowLeft, faCheck, faXmark, faPlaneDeparture, faCalendarCheck, faAddressCard, faSquareCheck, faHouse, faComment, faBookOpen, faChartSimple, faPaperclip, faEllipsisVertical)
}
