name: Trigger Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./build.yml
        with:
          branch: ${{ github.event.inputs.branch }}
